version: '3'

services:
  web:
    build: .
    command: python -m gunicorn diveguide_professional_api.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
      - ./www:/www
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 3306
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'
  nginx:
    image: nginx:1.19.0
    ports:
      - '80:80'
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./www:/www
    depends_on:
      - web

volumes:
  db_data:
  www:
