# Generated by Django 4.2 on 2023-04-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Professional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=64, verbose_name="First name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=64, verbose_name="Last name"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "male"), ("Female", "female")],
                        max_length=32,
                        verbose_name="Gender",
                    ),
                ),
                ("yoe", models.IntegerField(verbose_name="Years of experience")),
                (
                    "joined",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Joined the platform"
                    ),
                ),
                (
                    "certifications",
                    models.ManyToManyField(
                        to="professional.certification",
                        verbose_name="Certifications they hold",
                    ),
                ),
                (
                    "languages",
                    models.ManyToManyField(
                        to="professional.language", verbose_name="Languages spoken"
                    ),
                ),
                (
                    "schools",
                    models.ManyToManyField(
                        to="professional.school",
                        verbose_name="Schools they got certified with",
                    ),
                ),
                (
                    "specialties",
                    models.ManyToManyField(
                        to="professional.specialty",
                        verbose_name="Specialties they teach",
                    ),
                ),
            ],
        ),
    ]
