# Generated by Django 4.2 on 2023-04-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("professional", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="professional",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
    ]
