# Generated by Django 4.2 on 2023-04-20 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("professional", "0002_professional_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Review content")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "pro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="professional.professional",
                        verbose_name="Professional",
                    ),
                ),
            ],
        ),
    ]
