# Generated by Django 4.2 on 2023-04-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("professional", "0004_contactinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="member_number",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
