# Generated by Django 4.2 on 2023-04-20 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("professional", "0006_remove_school_member_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="professional",
            name="schools",
        ),
        migrations.CreateModel(
            name="SchoolMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "member_number",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "pro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="professional.professional",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="professional.school",
                    ),
                ),
            ],
        ),
    ]
